### ISSUE TITLE
TypeError: Button.__init__() got an unexpected keyword argument 'info'

### ISSUE THREAD

**Issue by C0b3lt** [x-CK-x/Dataset-Curation-Tool#35]
when using the downloaded run.bat I get this error
![Screenshot 2024-05-23 223929](https://github.com/x-CK-x/Dataset-Curation-Tool/assets/121405316/03708a00-af77-48a0-8afd-9899dc7916e5)

**Comment by x-CK-x** [comment]
the quick fix to this is just to change the gradio version to `3.50.2`  and then run the `run.bat` file with the --update flag

the long term solution was to leave it the gradio version as the most current one, since I'll be releasing something new very soon

**Comment by ProxyPlayerHD** [comment]
i had the same issue, but luckily got it working after some pain.
why is this so unnecessarily complicated?

after finding the folder where the locally install python is located, i manually force-reinstalled gradio with version 3.50.2.

but then when i try to run `run.bat --update` it just uses the cached 5.1.0.
then i tried to purge the cache but it didn't work (it worked but the gradio package wasn't in it somehow??? and it still existed after the purge)
then it also uninstalled 3.50.2 to automatically reinstall 5.1.0
i even tried changing the requirements.txt file to specifically ask for gradio 3.50.2 but the command uses some completely different requirements file and i cannot find it.

like, the requirements.txt in the folder is just at: `E:\Dataset-Curation-Tool\requirements.txt` but within `run.bat` it loads some file called `E:\Dataset-Curation-Tool\condaenv.<random 8 letter sequence>.requirements.txt` and it simply doesn't exist in the directory, where is that file coming from, and why is it different from the regular one??? is it caching the original file and then never refering to it again, if so, why?

.

anyways i have it working... for now.

i just manually reinstalled 3.50.2 again and then just did `run.bat`, NO --update because that will just mess stuff up again.

it would be nice if there was a commandline option to do a cache purge before it tries to install the packages, and maybe update the requirements.txt from `gradio` to `gradio==3.50.2` as a workaround (and also figure out why it's not using that file)

**Comment by x-CK-x** [comment]
@ProxyPlayerHD @C0b3lt https://github.com/x-CK-x/Dataset-Curation-Tool/releases/tag/v4.4.6
some changes, bug fixes and uninstaller run files
